manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: mctechnology17
      url-base: https://github.com/mctechnology17
    - name: whoop-t
      url-base: https://github.com/whoop-t
    - name: averymd
      url-base: https://github.com/averymd
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: nice-adventure-time
      remote: whoop-t
      revision: main
    - name: zmk-nice-oled
      remote: averymd
      revision: main
  self:
    path: config
